[package]
name = "finte"
version = "0.1.2"
edition = "2018"
description = "convert between integer and Rust enum"
license = "MIT"

[dependencies.finte-derive]
version = "0.1.2"
optional = true

[features]
default = [ "derive" ]
derive = [ "finte-derive" ]
