[package]
name = "finte-derive"
version = "0.2.0"
edition = "2018"
description = "#[derive(IntEnum)] support for finte"
repository = "https://github.com/hismito/finte"
license = "MIT"

[lib]
proc-macro = true

[dev-dependencies]
finte = { path = "../finte" }
